uploads = []
outputs = []

[[generated]]
id = "UUpqABIhDFYxNfK_OiEym"
uri = "file://artifacts/makerforge-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SBeVvyQeMIyGSXB8-cima"
uri = "file://artifacts/makerforge-mobile/assets/images/splash.png"
type = "image"
title = "generated_image"
